import { ThemeContent, ThemeMeta } from "./types";

export const THEMES_EN: Record<string, ThemeMeta> = {
  onepiece: {
    id: "onepiece",
    label: "One Piece",
    emoji: "⚓",
    gradient: "from-[#1f4d8f] to-[#63b0f4]",
    accentColor: "#1f4d8f",
    tags: ["Adventure", "Crew", "Voyage"],
  },
  naruto: {
    id: "naruto",
    label: "Naruto",
    emoji: "🍥",
    gradient: "from-[#d45b32] to-[#f2a45f]",
    accentColor: "#d45b32",
    tags: ["Willpower", "Teamwork", "Growth"],
  },
  shinchan: {
    id: "shinchan",
    label: "Crayon Shin-chan",
    emoji: "🖍️",
    gradient: "from-[#f59e0b] to-[#facc15]",
    accentColor: "#f59e0b",
    tags: ["Kindergarten", "Everyday", "Comedy"],
  },
  fma: {
    id: "fma",
    label: "Fullmetal Alchemist",
    emoji: "⚗️",
    gradient: "from-[#2c2f36] to-[#c6a15b]",
    accentColor: "#c6a15b",
    tags: ["Alchemy", "Brothers", "Sacrifice"],
  },
  aot: {
    id: "aot",
    label: "Attack on Titan",
    emoji: "🛡️",
    gradient: "from-[#1f2937] to-[#6b7280]",
    accentColor: "#1f2937",
    tags: ["Scout", "Walls", "Freedom"],
  },
};

export const CONTENTS_EN: Record<string, ThemeContent> = {
  onepiece: {
    questions: [
      { axis: "SN", prompt: "Before reaching Skypiea, how do you find the sky-island route?", options: [{ value: "S", label: "Trust the log pose and records, follow the verified route" }, { value: "N", label: "Read the Knock Up Stream timing and imagine a new path" }] },
      { axis: "EI", prompt: "If conflict erupts among crewmates in Water 7, you...", options: [{ value: "E", label: "Step in and calm the mood directly" }, { value: "I", label: "Observe first, then share the key points quietly" }] },
      { axis: "TF", prompt: "When deciding to storm Enies Lobby, you...", options: [{ value: "T", label: "Calculate CP9 strength and escape routes" }, { value: "F", label: "Prioritize Robin's \"I want to live\"" }] },
      { axis: "JP", prompt: "After Dressrosa, how do you choose the next course?", options: [{ value: "J", label: "Plan a route like Law and follow the schedule" }, { value: "P", label: "Move like Luffy, seize the moment" }] },
      { axis: "SN", prompt: "If Poneglyph decoding stalls, you...", options: [{ value: "S", label: "Reorganize the text and coordinates for solid clues" }, { value: "N", label: "Imagine the hidden meaning and historical links" }] },
      { axis: "EI", prompt: "Arriving at a festival (Skypiea/Fishman Island), you...", options: [{ value: "E", label: "Do a spontaneous performance to lift the mood" }, { value: "I", label: "Watch from a distance and step in only when needed" }] },
      { axis: "TF", prompt: "In a Marineford-scale war, you choose...", options: [{ value: "T", label: "The option that minimizes losses" }, { value: "F", label: "The option that protects bonds and loyalty" }] },
      { axis: "JP", prompt: "If you handle supplies and food, you...", options: [{ value: "J", label: "Make a list like Nami and stock up" }, { value: "P", label: "Source on the fly like Sanji" }] },
      { axis: "EI", prompt: "During a long voyage break on deck, you...", options: [{ value: "E", label: "Perform with Usopp and Brook" }, { value: "I", label: "Read and reflect like Robin" }] },
      { axis: "SN", prompt: "Lost in Alabasta's desert, you...", options: [{ value: "S", label: "Check the map and supplies first" }, { value: "N", label: "Use stars and wind flow to decide" }] },
      { axis: "TF", prompt: "When a crewmate makes a big mistake, you...", options: [{ value: "T", label: "Fix the damage first" }, { value: "F", label: "Comfort them first" }] },
      { axis: "JP", prompt: "To achieve a goal in Wano, you...", options: [{ value: "J", label: "Build a step-by-step roadmap" }, { value: "P", label: "Break through when a chance appears" }] },
      { axis: "EI", prompt: "Right before the first voyage, you...", options: [{ value: "E", label: "Mingle at the harbor and gather rumors" }, { value: "I", label: "Quietly check gear and roles" }] },
      { axis: "SN", prompt: "When analyzing an enemy ability, you...", options: [{ value: "S", label: "Summarize the patterns you have seen" }, { value: "N", label: "Predict awakenings and hidden powers" }] },
      { axis: "TF", prompt: "At a negotiation table, you...", options: [{ value: "T", label: "Calculate terms and benefits" }, { value: "F", label: "Consider trust and circumstances" }] },
      { axis: "JP", prompt: "When assigning roles to the crew, you...", options: [{ value: "J", label: "Assign clearly for efficiency" }, { value: "P", label: "Let roles form naturally by situation" }] },
    ],
    results: {
      ISTJ: { name: "Jinbe", desc: "A principled stabilizer who keeps the crew grounded.", longDesc: "Jinbe values duty, order, and loyalty. He stays calm in crises and anchors the team with steady judgment.", episodeNote: "After Marineford, he reminded Luffy to count what he still had and stand up again." },
      ISFJ: { name: "Chopper", desc: "A caring healer who protects others with quiet devotion.", longDesc: "Chopper is gentle, responsible, and willing to sacrifice to save others. He works patiently and keeps the crew safe.", episodeNote: "He vowed to heal any illness after Dr. Hiluluk's legacy in Drum Island." },
      INFJ: { name: "Nico Robin", desc: "A quiet seeker of truth with deep inner conviction.", longDesc: "Robin pursues meaning and history with calm insight. Beneath her reserve is a strong moral core and loyalty.", episodeNote: "She cried "I want to live!" at Enies Lobby, choosing trust and life." },
      INTJ: { name: "Trafalgar Law", desc: "A strategic planner who calculates the long game.", longDesc: "Law reads the battlefield and designs efficient outcomes. He suppresses emotion to execute his plan.", episodeNote: "His long revenge plan against Doflamingo showed cold precision." },
      ISTP: { name: "Roronoa Zoro", desc: "A silent executor who proves everything through action.", longDesc: "Zoro focuses on skill and results over words. He steps up in decisive moments without hesitation.", episodeNote: "At Thriller Bark, he took Luffy's pain and said, "Nothing happened."" },
      ISFP: { name: "Brook", desc: "A free spirit who turns loneliness into music.", longDesc: "Brook lives in the present with art and emotion. His gentle charm softens even tense moments.", episodeNote: "He kept his promise to Laboon, playing after 50 years of solitude." },
      INFP: { name: "Nefertari Vivi", desc: "A warm idealist who puts peace above victory.", longDesc: "Vivi leads with empathy and values harmony. She believes in people and refuses to abandon hope.", episodeNote: "She begged the battlefield to stop in Alabasta's war from the clock tower." },
      INTP: { name: "Franky", desc: "A creative engineer who builds the impossible.", longDesc: "Franky thrives on invention and bold ideas. He blends logic with imagination to protect the crew.", episodeNote: "He built the Thousand Sunny as a gift for the crew's future." },
      ESTP: { name: "Monkey D. Luffy", desc: "A fearless breaker who acts first and opens paths.", longDesc: "Luffy trusts instinct and charges forward. His bold action unblocks stalled situations.", episodeNote: "He stormed Marineford head-on to save Ace despite impossible odds." },
      ESFP: { name: "Nami", desc: "A lively navigator who reads the flow of people and seas.", longDesc: "Nami combines practical sense with social awareness. She steers the crew with realism and heart.", episodeNote: "She asked Luffy for help at Arlong Park, choosing trust over fear." },
      ENFP: { name: "Usopp", desc: "A lively dreamer who turns fear into courage.", longDesc: "Usopp uses imagination and heart to overcome fear. He inspires others when it matters most.", episodeNote: "As Sogeking, he fired at the World Government flag at Enies Lobby." },
      ENTP: { name: "Gol D. Roger", desc: "A visionary rebel who sparked a new era.", longDesc: "Roger challenged the world's limits and opened a new age of adventure.", episodeNote: "His final speech launched the Great Pirate Era." },
      ESTJ: { name: "Akainu", desc: "A strict enforcer who defends order at all costs.", longDesc: "Akainu is uncompromising and rule-driven, pushing absolute justice with force.", episodeNote: "He executed deserters during Marineford to uphold strict discipline." },
      ESFJ: { name: "Sanji", desc: "A devoted caretaker who feeds and protects the crew.", longDesc: "Sanji's loyalty shows through service and care. He steadies the team with warmth and resolve.", episodeNote: "He returned to the crew after revealing his true feelings at Whole Cake Island." },
      ENFJ: { name: "Silvers Rayleigh", desc: "A wise mentor who guides the next generation.", longDesc: "Rayleigh reads people's potential and helps them grow with calm confidence.", episodeNote: "He trained Luffy during the two-year timeskip." },
      ENTJ: { name: "Shanks", desc: "A decisive leader who balances strength and diplomacy.", longDesc: "Shanks leads with firm judgment and long-term vision, holding power without excess.", episodeNote: "He stopped the Marineford war with one decisive appearance." },
    },
  },
  naruto: {
    questions: [
      { axis: "SN", prompt: "If you must analyze an enemy jutsu, you...", options: [{ value: "S", label: "Track hand signs and chakra traces" }, { value: "N", label: "Infer hidden techniques and next variables" }] },
      { axis: "EI", prompt: "During Chunin Exam prep, you...", options: [{ value: "E", label: "Run mock battles with your team" }, { value: "I", label: "Train solo and refine your scrolls" }] },
      { axis: "TF", prompt: "When you must track Sasuke, you...", options: [{ value: "T", label: "Calculate risks and success rates" }, { value: "F", label: "Think of promises and bonds first" }] },
      { axis: "JP", prompt: "When making an operation plan, you...", options: [{ value: "J", label: "Build a Shikamaru-style step plan" }, { value: "P", label: "Adjust flexibly to field variables" }] },
      { axis: "SN", prompt: "If clues are scarce on a search mission, you...", options: [{ value: "S", label: "Follow footprints and physical traces" }, { value: "N", label: "Connect information and draw a route" }] },
      { axis: "EI", prompt: "While waiting before mission briefing, you...", options: [{ value: "E", label: "Lift team mood and ease tension" }, { value: "I", label: "Sort info quietly and focus" }] },
      { axis: "TF", prompt: "When facing an isolated enemy, you...", options: [{ value: "T", label: "End it quickly for the mission" }, { value: "F", label: "Look for a chance to reform them" }] },
      { axis: "JP", prompt: "If you run a training routine, you...", options: [{ value: "J", label: "Repeat on a fixed schedule" }, { value: "P", label: "Adjust to condition and missions" }] },
      { axis: "EI", prompt: "Right before a joint operation, you...", options: [{ value: "E", label: "Encourage teammates and raise energy" }, { value: "I", label: "Control breathing and sharpen focus" }] },
      { axis: "SN", prompt: "When using the battlefield terrain, you...", options: [{ value: "S", label: "Use nearby trees and rocks immediately" }, { value: "N", label: "Imagine the whole field and place a move" }] },
      { axis: "TF", prompt: "After battle, choose between finish or rescue?", options: [{ value: "T", label: "Resolve quickly to stabilize the situation" }, { value: "F", label: "Consider the other side's feelings" }] },
      { axis: "JP", prompt: "How do you share information?", options: [{ value: "J", label: "Document and report systematically" }, { value: "P", label: "Share instantly when needed" }] },
      { axis: "EI", prompt: "When a teammate vents their worries, you...", options: [{ value: "E", label: "Step in and talk it out" }, { value: "I", label: "Listen beside them and say only what's needed" }] },
      { axis: "SN", prompt: "When decoding a sealing-jutsu scroll, you...", options: [{ value: "S", label: "Follow the standard method exactly" }, { value: "N", label: "Look for hidden meaning and expansions" }] },
      { axis: "TF", prompt: "When choosing a team leader, you...", options: [{ value: "T", label: "Choose by skill and judgment" }, { value: "F", label: "Choose by trust and bonds" }] },
      { axis: "JP", prompt: "When you look at long-term goals, you...", options: [{ value: "J", label: "Build a roadmap and execute step by step" }, { value: "P", label: "Adjust direction whenever opportunities appear" }] },
    ],
    results: {
      ISTJ: { name: "Kakashi Hatake", desc: "A disciplined tactician with calm control.", longDesc: "Kakashi values rules and readiness, leading with steady judgment. He protects his team through preparation and restraint.", episodeNote: "He taught Team 7 that those who abandon friends are worse than trash." },
      ISFJ: { name: "Hinata Hyuga", desc: "A quiet protector with deep devotion.", longDesc: "Hinata is gentle yet strong, willing to risk everything for those she loves.", episodeNote: "She stepped in against Pain to protect Naruto, confessing her heart." },
      INFJ: { name: "Itachi Uchiha", desc: "A solemn idealist who carried the truth alone.", longDesc: "Itachi sacrificed himself for peace and his brother's future, guided by long vision.", episodeNote: "He tapped Sasuke's forehead and said goodbye with a smile." },
      INTJ: { name: "Shikamaru Nara", desc: "A brilliant strategist who wins with planning.", longDesc: "Shikamaru calculates outcomes and minimizes losses, leading with cool logic.", episodeNote: "He trapped Hidan with a perfect plan to avenge Asuma." },
      ISTP: { name: "Sai", desc: "A quiet analyst learning human bonds.", longDesc: "Sai stays practical and controlled, expressing himself through actions more than words.", episodeNote: "He finally smiled after understanding true friendship." },
      ISFP: { name: "Neji Hyuga", desc: "A calm prodigy who chose his own path.", longDesc: "Neji moved from fate-bound resignation to self-chosen freedom and sacrifice.", episodeNote: "He protected Naruto and Hinata in the war, choosing his own destiny." },
      INFP: { name: "Gaara", desc: "A wounded soul who learned empathy and peace.", longDesc: "Gaara grew from isolation to compassion, leading with quiet conviction.", episodeNote: "His speech united the allied shinobi forces." },
      INTP: { name: "Orochimaru", desc: "A ruthless researcher obsessed with knowledge.", longDesc: "Orochimaru pursues truth beyond ethics, experimenting without limits.", episodeNote: "He kept plotting even after losing his arms, driven by obsession." },
      ESTP: { name: "Naruto Uzumaki", desc: "A bold doer who breaks limits with action.", longDesc: "Naruto charges forward with belief and energy, changing hearts through results.", episodeNote: "He saved the village during the Pain invasion as a true hero." },
      ESFP: { name: "Rock Lee", desc: "A passionate fighter who proves effort beats talent.", longDesc: "Lee lives through training and heart, inspiring others with relentless effort.", episodeNote: "He dropped his ankle weights against Gaara, shocking everyone." },
      ENFP: { name: "Jiraiya", desc: "A free spirit mentor and seeker of peace.", longDesc: "Jiraiya explores the world with curiosity and faith, nurturing his students.", episodeNote: "He died passing the key to Naruto with a smile." },
      ENTP: { name: "Obito Uchiha", desc: "A radical visionary who tried to rewrite reality.", longDesc: "Obito offered an extreme solution to pain, reshaping the world in his image.", episodeNote: "He declared the Fourth Great Ninja War from behind a mask." },
      ESTJ: { name: "Tsunade", desc: "A decisive leader who bears the village's weight.", longDesc: "Tsunade keeps order and acts fast in crisis, balancing care with authority.", episodeNote: "She healed the village through Katsuyu during Pain's attack." },
      ESFJ: { name: "Sakura Haruno", desc: "A reliable supporter who heals and steadies the team.", longDesc: "Sakura protects and sustains others with discipline and heart.", episodeNote: "She unlocked her full strength in the final battle, proving her growth." },
      ENFJ: { name: "Yamato", desc: "A calm mediator who stabilizes the team.", longDesc: "Yamato balances strength and care, guiding Team 7 with steady leadership.", episodeNote: "He soothed Naruto's rampage with Wood Style and trust." },
      ENTJ: { name: "Madara Uchiha", desc: "A dominant strategist chasing absolute order.", longDesc: "Madara drives a grand vision with overwhelming power and control.", episodeNote: "His meteor summon left the battlefield in despair." },
    },
  },
  fma: {
    questions: [
      { axis: "EI", prompt: "You arrive in Central City and smell great food in the market. You...", options: [{ value: "E", label: "Ask locals for the best menu and chat" }, { value: "I", label: "Sit quietly, read the menu, and organize your notes" }] },
      { axis: "EI", prompt: "Colonel Mustang calls a forced team dinner. You...", options: [{ value: "E", label: "Lead the mood and recharge with everyone" }, { value: "I", label: "Watch the clock and plan your quiet exit" }] },
      { axis: "EI", prompt: "At the State Alchemist exam waiting room, you...", options: [{ value: "E", label: "Chat and exchange info with others" }, { value: "I", label: "Review formulas and keep to yourself" }] },
      { axis: "EI", prompt: "You finally found a crucial clue. You...", options: [{ value: "E", label: "Run to share the news loudly" }, { value: "I", label: "Celebrate quietly and reflect alone" }] },
      { axis: "SN", prompt: "You discover an old grimoire with a strange transmutation circle. You notice...", options: [{ value: "S", label: "Ink thickness, lines, and paper texture" }, { value: "N", label: "What hidden meaning or taboo it could imply" }] },
      { axis: "SN", prompt: "On a deserted island, your teacher says "One is all, all is one." You think...", options: [{ value: "S", label: "It describes the food chain and material cycle" }, { value: "N", label: "It points to a larger invisible truth" }] },
      { axis: "SN", prompt: "Heading to Briggs with a vague map, you...", options: [{ value: "S", label: "Verify terrain and compass for a solid path" }, { value: "N", label: "Trust the overall direction and intuition" }] },
      { axis: "SN", prompt: "When researching new alchemy theory, you enjoy...", options: [{ value: "S", label: "Repeated experiments that yield precise results" }, { value: "N", label: "Connecting two distant ideas into a new insight" }] },
      { axis: "TF", prompt: "Facing the Tucker chimera, your first words are...", options: [{ value: "T", label: "This violates ethics. We must solve it fast." }, { value: "F", label: "How could a human do this... I am so sorry." }] },
      { axis: "TF", prompt: "You learn the Philosopher's Stone needs many human lives. You...", options: [{ value: "T", label: "Coldly evaluate the cost and logic" }, { value: "F", label: "Reject it as unacceptable" }] },
      { axis: "TF", prompt: "A colleague failed an experiment and is crushed. You...", options: [{ value: "T", label: "Point out the wrong equation to fix" }, { value: "F", label: "Comfort them before anything else" }] },
      { axis: "TF", prompt: "A friend seeks dangerous revenge. You...", options: [{ value: "T", label: "Tell them it is irrational and self-destructive" }, { value: "F", label: "Beg them to stop for everyone's sake" }] },
      { axis: "JP", prompt: "You must deploy urgently. Your bag is...", options: [{ value: "J", label: "Tools, med kit, and rations perfectly organized" }, { value: "P", label: "Stuffed quickly; you will improvise later" }] },
      { axis: "JP", prompt: "Your research notes are...", options: [{ value: "J", label: "Cleanly structured from start to finish" }, { value: "P", label: "Scattered ideas you will decode later" }] },
      { axis: "JP", prompt: "A Homunculus attacks suddenly. You...", options: [{ value: "J", label: "Follow a prepared emergency protocol" }, { value: "P", label: "Improvise using terrain and opportunity" }] },
      { axis: "JP", prompt: "Homework due tomorrow from your teacher. You...", options: [{ value: "J", label: "Finish today and review" }, { value: "P", label: "Push it to the last minute" }] },
    ],
    results: {
      ENTP: { name: "Edward Elric", desc: "A sharp innovator who breaks old rules.", longDesc: "Edward adapts fast and challenges fixed systems, pushing forward with bold logic.", episodeNote: "He flipped battles with quick transmutations and refused to give up." },
      INFP: { name: "Alphonse Elric", desc: "A gentle idealist with strong inner values.", longDesc: "Alphonse protects others with empathy and quiet courage.", episodeNote: "He sacrificed himself to open the path for his brother." },
      ENTJ: { name: "Roy Mustang", desc: "A strategic commander with big ambitions.", longDesc: "Roy leads with clear vision and decisive control, pushing reform through results.", episodeNote: "He pursued change in the military while hiding his true resolve." },
      ISFJ: { name: "Riza Hawkeye", desc: "A loyal protector who steadies the team.", longDesc: "Riza is disciplined and devoted, supporting the mission with calm precision.", episodeNote: "She risked everything to guard Mustang's ideals." },
      ISTP: { name: "Winry Rockbell", desc: "A practical maker who fixes what matters.", longDesc: "Winry solves problems through skill and hands-on care, focused on real outcomes.", episodeNote: "She repaired automail overnight to get her friends moving again." },
      ENFJ: { name: "Maes Hughes", desc: "A warm connector who keeps people close.", longDesc: "Hughes lifts the team with empathy and brings people together.", episodeNote: "He shared both joy and truth to keep everyone united." },
      ESTJ: { name: "Olivier Armstrong", desc: "A strict leader who upholds order.", longDesc: "Olivier enforces discipline and efficiency, leading with iron resolve.", episodeNote: "She kept Briggs strong with decisive authority." },
      ESFJ: { name: "Alex Louis Armstrong", desc: "A passionate supporter who energizes allies.", longDesc: "Alex encourages others with warmth and proud strength.", episodeNote: "His enthusiasm lifted morale in critical moments." },
      INFJ: { name: "Van Hohenheim", desc: "A reflective wanderer with long vision.", longDesc: "Hohenheim carries a distant perspective and acts for the future.", episodeNote: "He chose a final path after long solitude and reflection." },
      ISTJ: { name: "Scar", desc: "A principled executor who sticks to his path.", longDesc: "Scar follows a firm code, acting with restraint and purpose.", episodeNote: "He completed his mission without wavering." },
      ESTP: { name: "Ling Yao", desc: "A bold opportunist with quick instincts.", longDesc: "Ling moves fast and adapts instantly, chasing his goals head-on.", episodeNote: "He flipped danger into advantage through daring choices." },
      ENFP: { name: "Mei Chang", desc: "A cheerful believer who pursues hope.", longDesc: "Mei brings bright energy and keeps moving toward her ideals.", episodeNote: "She charged forward with small stature but huge resolve." },
      INTJ: { name: "Pride (Selim)", desc: "A cold strategist who controls the board.", longDesc: "Pride manipulates from the shadows and calculates every variable.", episodeNote: "He dominated fights by reading weaknesses precisely." },
      INTP: { name: "Zolf J. Kimblee", desc: "A detached thinker with a dangerous aesthetic.", longDesc: "Kimblee follows his own logic and treats destruction as art.", episodeNote: "He acted without hesitation to prove his philosophy." },
      ISFP: { name: "Lan Fan", desc: "A loyal fighter who proves feelings through action.", longDesc: "Lan Fan rarely speaks but acts with fierce devotion and precision.", episodeNote: "She risked herself to protect her lord." },
      ESFP: { name: "Greed", desc: "A flashy free spirit who loves desire and freedom.", longDesc: "Greed thrives on pleasure and bold expression, yet keeps his own code.", episodeNote: "He chose freedom even in the face of loss." },
    },
  },
  aot: {
    questions: [
      { axis: "EI", prompt: "On a rare day off, the squad is drinking loudly at a tavern. You...", options: [{ value: "E", label: "Join in, tell stories, and blow off steam" }, { value: "I", label: "Stay quiet, tune your gear, or walk alone" }] },
      { axis: "EI", prompt: "New recruits arrive. As a senior, you...", options: [{ value: "E", label: "Approach first and share tips" }, { value: "I", label: "Watch from afar and help only when needed" }] },
      { axis: "EI", prompt: "During a forest break on an expedition, you...", options: [{ value: "E", label: "Chat to keep morale up" }, { value: "I", label: "Scan the area andorganize your thoughts" }] },
      { axis: "EI", prompt: "Invited to a victory party, you...", options: [{ value: "E", label: "Circulate and meet many people" }, { value: "I", label: "Stay with a small group at one table" }] },
      { axis: "SN", prompt: "When facing a Titan, you focus on...", options: [{ value: "S", label: "Size, speed, distance to the nape" }, { value: "N", label: "The hidden reason it appeared" }] },
      { axis: "SN", prompt: "Armin talks about the sea. You think...", options: [{ value: "S", label: "What would it feel like in real life?" }, { value: "N", label: "Freedom and truth await beyond the walls" }] },
      { axis: "SN", prompt: "When learning a new ODM technique, you...", options: [{ value: "S", label: "Copy the instructor step by step" }, { value: "N", label: "Understand the principle and adapt" }] },
      { axis: "SN", prompt: "Rumors say peace may break. You...", options: [{ value: "S", label: "Secure supplies and check gas" }, { value: "N", label: "Imagine future survival scenarios" }] },
      { axis: "TF", prompt: "Erwin orders a suicidal charge. You...", options: [{ value: "T", label: "Accept the logic for victory" }, { value: "F", label: "Grieve for the lives being lost" }] },
      { axis: "TF", prompt: "A close teammate makes a critical mistake. You...", options: [{ value: "T", label: "Point out the error directly" }, { value: "F", label: "Comfort them first" }] },
      { axis: "TF", prompt: "Only one person can get the Titan serum. You...", options: [{ value: "T", label: "Choose the most useful for survival" }, { value: "F", label: "Choose the one you care for most" }] },
      { axis: "TF", prompt: "You see Eren driven by revenge. You say...", options: [{ value: "T", label: "Revenge is inefficient. Stay calm." }, { value: "F", label: "I understand your pain. Don't lose yourself." }] },
      { axis: "JP", prompt: "The day before an expedition, you...", options: [{ value: "J", label: "Check the list three times and sleep early" }, { value: "P", label: "Pack roughly and stay up talking" }] },
      { axis: "JP", prompt: "A sudden abnormal Titan appears. You...", options: [{ value: "J", label: "Follow a planned emergency protocol" }, { value: "P", label: "Improvise with terrain" }] },
      { axis: "JP", prompt: "Levi orders a cleanup. You...", options: [{ value: "J", label: "Clean in a strict, systematic order" }, { value: "P", label: "Start anywhere and go with the flow" }] },
      { axis: "JP", prompt: "The route must change mid-mission. You...", options: [{ value: "J", label: "Feel stressed by unpredictability" }, { value: "P", label: "Feel energized by the new chance" }] },
    ],
    results: {
      INTJ: { name: "Erwin Smith", desc: "A long-range strategist who sacrifices for the goal.", longDesc: "Erwin leads with vision and calculation, accepting painful costs for future victory.", episodeNote: "He charged with full awareness of his own death for the truth." },
      ENTJ: { name: "Zeke Yeager", desc: "A controlling leader who pursues a grand plan.", longDesc: "Zeke values systems and outcomes, moving pieces to complete his strategy.", episodeNote: "He orchestrated battles with cold precision toward his goal." },
      INFJ: { name: "Armin Arlert", desc: "A thoughtful tactician who sees the bigger meaning.", longDesc: "Armin reads people and situations deeply, seeking hope beyond conflict.", episodeNote: "He negotiated under pressure using insight rather than force." },
      ENFJ: { name: "Falco Grice", desc: "A warm mediator who seeks peace.", longDesc: "Falco empathizes with others and chooses cooperation even in war.", episodeNote: "He acted to protect everyone despite the sides." },
      INFP: { name: "Bertholdt Hoover", desc: "A quiet soul torn between duty and guilt.", longDesc: "Bertholdt carries inner conflict and chooses a painful path with reluctance.", episodeNote: "He confessed his burden while still fulfilling his role." },
      ENFP: { name: "Sasha Braus", desc: "A bright spirit who keeps people smiling.", longDesc: "Sasha brings humor and warmth, lifting morale in dark times.", episodeNote: "She lightened tense moments with her fearless appetite and jokes." },
      ISFP: { name: "Eren Yeager", desc: "A passionate fighter driven by freedom.", longDesc: "Eren follows his emotions and ideals with explosive intensity.", episodeNote: "He shouted for freedom and charged toward the world beyond the walls." },
      ESFP: { name: "Connie Springer", desc: "A lively optimist who adapts quickly.", longDesc: "Connie keeps energy high and adjusts fast to chaos.", episodeNote: "He supported teammates with quick humor and flexibility." },
      ISTJ: { name: "Mikasa Ackerman", desc: "A steady guardian who never wavers.", longDesc: "Mikasa executes duties with absolute focus and loyalty.", episodeNote: "She protected her team with unwavering resolve in every battle." },
      ESTJ: { name: "Jean Kirstein", desc: "A practical commander who grows into leadership.", longDesc: "Jean balances realism and responsibility, guiding others through hard calls.", episodeNote: "He led the squad forward during the Trost battle." },
      ISFJ: { name: "Historia Reiss", desc: "A gentle protector who chooses her own path.", longDesc: "Historia acts with care and quiet courage, accepting responsibility for others.", episodeNote: "She chose to become queen for the people's future." },
      ESFJ: { name: "Reiner Braun", desc: "A dependable big brother who holds the group together.", longDesc: "Reiner builds bonds and takes responsibility even under inner conflict.", episodeNote: "He supported his comrades while struggling with his role." },
      INTP: { name: "Pieck Finger", desc: "A calm analyst who reads the battlefield.", longDesc: "Pieck sees patterns quickly and chooses the most efficient move.", episodeNote: "She stabilized the field through sharp observation and timing." },
      ENTP: { name: "Hange Zoe", desc: "An inquisitive innovator who challenges limits.", longDesc: "Hange pursues knowledge with fearless curiosity and bold experiments.", episodeNote: "Her Titan research pushed humanity's understanding forward." },
      ISTP: { name: "Levi Ackerman", desc: "A precise executor who chooses the shortest path.", longDesc: "Levi acts with clean efficiency, never wasting motion.", episodeNote: "He dominated battles through perfect timing and skill." },
      ESTP: { name: "Ymir (104th)", desc: "A blunt realist who lives for the present.", longDesc: "Ymir faces reality and acts quickly for what she values.", episodeNote: "She chose her own truth even against the world's expectations." },
    },
  },
  shinchan: {
    questions: [
      { axis: "EI", prompt: "It is your first day at Futaba Kindergarten. What do you do?", options: [{ value: "E", label: "Walk up first, introduce yourself, and ask to play together." }, { value: "I", label: "Wait for someone to speak first, or play quietly in the corner." }] },
      { axis: "EI", prompt: "Action Mask is on TV and it is amazing! You...", options: [{ value: "E", label: '"Waaa! Action Beam!" Shout, dance, and tell everyone.' }, { value: "I", label: 'Smile quietly and think, "Action Mask is the best."' }] },
      { axis: "EI", prompt: "Shin-chan's family invited you to a camping trip. What will you do?", options: [{ value: "E", label: "Play, grill, and lift the mood for everyone." }, { value: "I", label: "Read inside the tent or watch the fire quietly." }] },
      { axis: "EI", prompt: "A stranger asks you for directions. You...", options: [{ value: "E", label: "Explain in detail with friendly chat." }, { value: "I", label: "Give short info and keep going." }] },
      { axis: "SN", prompt: "You bought Chocobi. What are you looking forward to?", options: [{ value: "S", label: "The crunchy texture and sweet taste." }, { value: "N", label: "The surprise of a rare sticker." }] },
      { axis: "SN", prompt: "Bo-chan shows a strange rock. You...", options: [{ value: "S", label: "Observe its smooth, round shape." }, { value: "N", label: "Imagine it as a dinosaur egg." }] },
      { axis: "SN", prompt: "Mom says "Run an errand!" You...", options: [{ value: "S", label: "Check the list and head straight to the store." }, { value: "N", label: "Get distracted and forget the list." }] },
      { axis: "SN", prompt: "Writing a kindergarten play script, you...", options: [{ value: "S", label: "Use a familiar story and keep it realistic." }, { value: "N", label: "Pitch an alien invasion twist." }] },
      { axis: "TF", prompt: "Masao lost his toy and is crying. You...", options: [{ value: "T", label: "Ask where he last saw it and search." }, { value: "F", label: "Comfort him first." }] },
      { axis: "TF", prompt: "Shin-chan caused an accident. You...", options: [{ value: "T", label: "Explain why it is dangerous." }, { value: "F", label: "Appeal to feelings." }] },
      { axis: "TF", prompt: "Nene's play script feels bad. You...", options: [{ value: "T", label: "Suggest edits directly." }, { value: "F", label: "Go along to protect her feelings." }] },
      { axis: "TF", prompt: "A friend asks about a new haircut. You...", options: [{ value: "T", label: "Answer with facts." }, { value: "F", label: "Compliment first." }] },
      { axis: "JP", prompt: "Saturday morning, you...", options: [{ value: "J", label: "Follow a plan." }, { value: "P", label: "Start the day as it comes." }] },
      { axis: "JP", prompt: "Mom orders you to clean your room. You...", options: [{ value: "J", label: "Organize step by step." }, { value: "P", label: "Get distracted and delay." }] },
      { axis: "JP", prompt: "Kasukabe Defense Force meeting time! You...", options: [{ value: "J", label: "Arrive early and wait." }, { value: "P", label: "Rush in late." }] },
      { axis: "JP", prompt: "Packing for a family trip. You...", options: [{ value: "J", label: "Make a list and pack carefully." }, { value: "P", label: "Pack only big items and go." }] },
    ],
    results: {
      ENFP: { name: "Shin-chan (Shinnosuke)", desc: "A playful idea machine with wild spontaneity.", longDesc: "Shin-chan turns every moment into a game and connects with people instantly.", episodeNote: "His "Yay!" moments flip the room's mood in seconds." },
      ENTJ: { name: "Kazama", desc: "A goal-driven leader with strong plans.", longDesc: "Kazama pushes toward achievement and keeps order when chaos appears.", episodeNote: "He follows strict study schedules to reach elite goals." },
      ESFJ: { name: "Nene", desc: "A group organizer who leads with social control.", longDesc: "Nene reads the room and shapes the group's roles and rules.", episodeNote: "Her "real" pretend-play shows her leadership style." },
      ISFP: { name: "Masao", desc: "A gentle artist with quiet sensitivity.", longDesc: "Masao avoids conflict and shows warmth in subtle ways.", episodeNote: "He often escapes into drawing or comics." },
      ISTJ: { name: "Bo-chan", desc: "A calm, steady rule-keeper.", longDesc: "Bo-chan sticks to routines and brings stability to the group.", episodeNote: "He quietly studies rocks with unwavering focus." },
      ESTJ: { name: "Misae", desc: "A practical manager who runs the household.", longDesc: "Misae keeps rules and finances in order with decisive action.", episodeNote: "She tracks sales and budgets with precision." },
      INTP: { name: "Hiroshi", desc: "A logical dad who shines in crises.", longDesc: "Hiroshi stays rational under pressure and makes the hard calls.", episodeNote: "He often becomes the steady core in the movies." },
      ISTP: { name: "Shiro", desc: "A silent problem solver.", longDesc: "Shiro handles situations with quick, practical judgment.", episodeNote: "He notices danger early and fixes things quietly." },
      INFJ: { name: "Nanako", desc: "A warm, insightful helper.", longDesc: "Nanako sees the sincerity behind Shin-chan's antics.", episodeNote: "Her gentle smile calms him instantly." },
      ESTP: { name: "Himawari", desc: "An action-first adventurer.", longDesc: "Himawari charges toward what she wants without hesitation.", episodeNote: "She chases sparkly things and handsome men instantly." },
      ENTP: { name: "Buriburizaemon", desc: "A witty opportunist with clever logic twists.", longDesc: "He bends arguments to his advantage and enjoys debate.", episodeNote: ""I am always on the stronger side!" is his signature line." },
      ENFJ: { name: "Action Mask", desc: "A heroic leader who inspires courage.", longDesc: "Action Mask motivates others to choose justice and act bravely.", episodeNote: "He arrives at the perfect time to boost everyone's spirit." },
      INTJ: { name: "Ai-chan", desc: "A strategic planner who executes with precision.", longDesc: "Ai-chan calculates her moves to reach her goals.", episodeNote: "Her planned approaches to Shin-chan reveal her strategy." },
      INFP: { name: "Ms. Matsuzaka", desc: "A gentle idealist who cares for children.", longDesc: "She leads with empathy and quiet devotion.", episodeNote: "She comforts kids with warm patience." },
      ESFP: { name: "Ms. Yoshinaga", desc: "A vibrant entertainer who loves attention.", longDesc: "She brings bright energy and enjoys style and fun.", episodeNote: "Her excitement about fashion is unmistakable." },
      ISFJ: { name: "Principal", desc: "A devoted guardian with a tough exterior.", longDesc: "He protects the kids with steady responsibility.", episodeNote: "He steps in quietly when the children are at risk." },
    },
  },
};
