
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./data.ts",
    "./constants.tsx",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-ibm-plex)'],
        serif: ['var(--font-noto-serif)'],
        slab: ['var(--font-roboto-slab)'],
      },
    },
  },
  // 동적으로 생성되는 클래스들이 빌드 시 누락되지 않도록 안전 목록에 추가
  safelist: [
    'from-[#1f4d8f]',
    'to-[#63b0f4]',
    'from-[#d45b32]',
    'to-[#f2a45f]',
    'from-[#dc2626]',
    'via-[#dc2626]',
    'to-[#2563eb]',
    'from-[#facc15]',
    'via-[#eab308]',
    'to-[#a16207]',
    'from-red-600',
    'to-blue-600',
    'to-slate-900',
    'from-indigo-700',
    'to-cyan-500',
    'to-white',
    'via-slate-900',
    'via-sky-400',
    'to-indigo-500',
    'from-red-500',
    'via-rose-500',
    'to-orange-100',
    'from-slate-300',
    'via-slate-500',
    'to-slate-800',
    'from-[#ef4444]',
    'via-[#1f2937]',
    'via-[#fecaca]',
    'via-[#ffffff]',
    'from-60%',
    'to-[#ef4444]',
    'to-[#f3f4f6]',
    'to-[#fff5f5]',
    'to-[#ffffff]',
    'from-[#e5e7eb]',
    'via-[#94a3b8]',
    'to-[#334155]',
    'bg-gradient-to-br',
    'bg-gradient-to-r',
    'bg-gradient-to-bl'
  ],
  plugins: [],
}
