import type { ThemeContent, ThemeMeta } from "@/types";

export const POKEMON_THEME_KO: ThemeMeta = {
  id: "pokemon",
  label: "포켓몬 1-2세대",
  emoji: "⚡",
  gradient: "from-[#ef4444] to-[#facc15]",
  accentColor: "#ef4444",
  tags: ["관동", "성도", "포켓몬"],
};

export const POKEMON_CONTENT_KO: ThemeContent = {
  questions: [
    { axis: "EI", prompt: "드디어 모험의 시작! 태초마을을 떠나며 당신이 처음 한 생각은?", options: [{ value: "E", label: "빨리 상록숲에 가서 다른 트레이너들과 배틀하고 친구를 사귀어야지!" }, { value: "I", label: "일단 풀숲에서 조용히 내 포켓몬과 유대감을 쌓으며 레벨업부터 해야겠다." }] },
    { axis: "EI", prompt: "포켓몬 센터에 들렀을 때, 당신의 행동은?", options: [{ value: "E", label: "다른 트레이너들에게 먼저 말을 걸며 정보를 교환한다." }, { value: "I", label: "구석에서 도감을 정리하거나 치료만 받고 얼른 나온다." }] },
    { axis: "EI", prompt: "자전거를 타던 중 누군가 승부를 걸어왔다. 당신은?", options: [{ value: "E", label: "좋아! 내 포켓몬의 실력을 보여주지! 신나게 배틀한다." }, { value: "I", label: "귀찮지만 침착하게 배틀하고 끝나면 조용히 갈 길 간다." }] },
    { axis: "EI", prompt: "관동에서 성도로 넘어가는 큰 배를 탔다. 당신은?", options: [{ value: "E", label: "배를 돌아다니며 사람들과 인사하고 분위기를 즐긴다." }, { value: "I", label: "갑판에서 조용히 다음 체육관 전략을 구상한다." }] },
    { axis: "SN", prompt: "풀숲에서 흔들리는 소리가 났다. 먼저 드는 생각은?", options: [{ value: "S", label: "구구나 꼬렛일 거야. 레벨도 대략 예상 가능해." }, { value: "N", label: "전설 포켓몬일 수도 있지 않을까? 잡을 방법은?" }] },
    { axis: "SN", prompt: "오박사님이 도감을 완성하라고 했다. 당신의 목표는?", options: [{ value: "S", label: "눈앞의 포켓몬을 차근차근 잡아 도감 번호를 채운다." }, { value: "N", label: "서식과 생태, 전설 포켓몬의 미스터리를 파헤친다." }] },
    { axis: "SN", prompt: "미케나 유적과 안농 문자를 발견했다. 당신의 반응은?", options: [{ value: "S", label: "보이는 글자와 단서를 하나씩 정확히 맞춰본다." }, { value: "N", label: "고대 문자와 세계의 기원 연결을 상상한다." }] },
    { axis: "SN", prompt: "새로운 기술을 가르칠 때 기준은?", options: [{ value: "S", label: "위력·명중률이 검증된 안정적인 기술을 고른다." }, { value: "N", label: "상대를 흔들 수 있는 변칙적 기술을 시도한다." }] },
    { axis: "TF", prompt: "라이벌과의 배틀에서 졌다. 첫마디는?", options: [{ value: "T", label: "원인부터 분석해서 다음 카운터를 준비한다." }, { value: "F", label: "포켓몬들의 마음을 먼저 걱정하며 다독인다." }] },
    { axis: "TF", prompt: "로켓단이 포켓몬을 괴롭히는 장면을 봤다. 당신은?", options: [{ value: "T", label: "명백한 위반이니 논리적으로 제압하고 막는다." }, { value: "F", label: "불쌍한 포켓몬이 먼저 보여 감정적으로 뛰어든다." }] },
    { axis: "TF", prompt: "동료가 약한 포켓몬을 방생하겠다고 한다. 당신은?", options: [{ value: "T", label: "효율만 보면 더 강한 포켓몬을 찾는 게 맞다고 본다." }, { value: "F", label: "함께한 포켓몬은 끝까지 책임져야 한다고 말한다." }] },
    { axis: "TF", prompt: "포켓몬과 친밀도를 올리는 최고의 방법은?", options: [{ value: "T", label: "배틀 성과와 훈련 효율로 객관적 유대감을 쌓는다." }, { value: "F", label: "열매를 주고 말을 걸며 따뜻한 교감을 쌓는다." }] },
    { axis: "JP", prompt: "체육관 도전 전 준비 상태는?", options: [{ value: "J", label: "상성·아이템·순서까지 완벽하게 맞춘 뒤 입장한다." }, { value: "P", label: "대충 챙기고 일단 부딪히며 조정한다." }] },
    { axis: "JP", prompt: "동굴(달맞이산/돌산터널)에 들어갈 때 당신은?", options: [{ value: "J", label: "규칙을 정하고 경로를 체계적으로 따라간다." }, { value: "P", label: "발길 닿는 대로 탐험하며 출구를 찾는다." }] },
    { axis: "JP", prompt: "포켓몬 가방(아이템 창)의 정리 상태는?", options: [{ value: "J", label: "카테고리별로 깔끔하게 정리되어 있다." }, { value: "P", label: "필요한 건 찾을 수 있지만 전체는 자유분방하다." }] },
    { axis: "JP", prompt: "모험의 최종 목표를 세울 때 당신은?", options: [{ value: "J", label: "뱃지와 리그 일정까지 구체적으로 계획한다." }, { value: "P", label: "여행하며 기회를 만나 자연스럽게 목표를 이룬다." }] },
  ],
  results: {
    ISTJ: { name: "망나뇽", desc: "바다의 수호자. 성실하고 책임감이 강한 든든한 조력자.", longDesc: "ISTJ인 당신은 약속과 원칙을 지키며 꾸준히 성과를 쌓는 타입입니다. 망나뇽처럼 조용하지만 끝까지 책임을 다하며 팀의 안정성을 높입니다." },
    ISFJ: { name: "해피너스", desc: "친절한 간호사. 헌신과 배려로 주변을 돌보는 따뜻한 보호자.", longDesc: "ISFJ인 당신은 타인의 상태를 세심하게 살피고 안정감을 제공하는 데 강합니다. 해피너스처럼 보이지 않는 곳에서 관계를 지탱하는 힘이 큽니다." },
    INFJ: { name: "뮤", desc: "신비로운 기원. 조용히 세상을 관찰하는 통찰가.", longDesc: "INFJ인 당신은 표면보다 의미와 흐름을 읽으며 장기적인 비전을 중시합니다. 뮤처럼 희귀한 관점으로 사람과 상황을 연결하는 능력이 돋보입니다." },
    INTJ: { name: "뮤츠", desc: "냉철한 사색가. 완벽한 논리와 전략을 추구하는 독립형.", longDesc: "INTJ인 당신은 복잡한 문제를 구조화해 최적해를 설계하는 데 강합니다. 뮤츠처럼 강한 집중력과 장기 전략으로 목표를 현실화합니다." },
    ISTP: { name: "스라크", desc: "고독한 무사. 정교한 기술과 실전 감각이 뛰어난 해결사.", longDesc: "ISTP인 당신은 상황을 빠르게 파악하고 즉시 실행 가능한 해법을 찾습니다. 스라크처럼 말보다 행동으로 실력을 증명하는 타입입니다." },
    ISFP: { name: "메타몽", desc: "유연한 예술가. 조용하지만 감각적이고 적응력이 뛰어남.", longDesc: "ISFP인 당신은 자신의 감정과 가치에 진실하면서도 환경 변화에 유연하게 반응합니다. 메타몽처럼 부드럽지만 독창적인 방식으로 존재감을 드러냅니다." },
    INFP: { name: "토게피", desc: "순수한 이상주의자. 평화와 진심을 소중히 여기는 몽상가.", longDesc: "INFP인 당신은 성과보다 의미와 진정성을 중시하며 공감력이 깊습니다. 토게피처럼 따뜻한 분위기를 만들고 사람들의 마음을 부드럽게 연결합니다." },
    INTP: { name: "후딘", desc: "초능력 분석가. 논리와 실험으로 본질을 파고드는 탐구자.", longDesc: "INTP인 당신은 복잡한 원리를 분해하고 새로운 해석을 만드는 데 탁월합니다. 후딘처럼 깊은 사고와 지적 호기심이 강한 유형입니다." },
    ESTP: { name: "윈디", desc: "거침없는 실행가. 속도와 용기로 돌파하는 행동형.", longDesc: "ESTP인 당신은 기회 포착이 빠르고 실전에서 강한 존재감을 보입니다. 윈디처럼 움직이며 답을 찾고 흐름을 바꾸는 힘이 큽니다." },
    ESFP: { name: "피카츄", desc: "슈퍼스타. 밝은 에너지로 사람들을 즐겁게 만드는 분위기형.", longDesc: "ESFP인 당신은 즉시 현장 분위기를 읽고 사람들과 빠르게 연결됩니다. 피카츄처럼 활력과 친근함으로 팀의 사기를 끌어올립니다." },
    ENFP: { name: "꼬부기", desc: "재기발랄한 리더. 호기심과 사교성으로 판을 여는 활력형.", longDesc: "ENFP인 당신은 새로운 아이디어와 사람 사이를 연결하며 동기를 만듭니다. 꼬부기처럼 장난기와 리더십을 함께 가진 창의적 추진형입니다." },
    ENTP: { name: "팬텀", desc: "유쾌한 전략가. 기발한 발상으로 고정관념을 깨는 변칙형.", longDesc: "ENTP인 당신은 토론과 실험을 통해 새로운 가능성을 빠르게 시험합니다. 팬텀처럼 재치와 전략으로 상대의 예측을 흔드는 능력이 뛰어납니다." },
    ESTJ: { name: "괴력몬", desc: "엄격한 관리자. 규율과 성과를 중시하는 실행 리더.", longDesc: "ESTJ인 당신은 질서와 역할을 명확히 정리해 팀 실행력을 높입니다. 괴력몬처럼 강한 책임감과 추진력으로 결과를 만들어냅니다." },
    ESFJ: { name: "픽시", desc: "다정한 사교가. 조화와 배려로 공동체를 돌보는 조율형.", longDesc: "ESFJ인 당신은 사람의 감정을 세밀하게 읽고 관계의 균형을 잡는 데 강합니다. 픽시처럼 따뜻한 소통으로 분위기를 안정시키는 유형입니다." },
    ENFJ: { name: "루기아", desc: "바다의 신. 카리스마와 보호 본능을 가진 선도형 리더.", longDesc: "ENFJ인 당신은 사람들의 잠재력을 발견하고 함께 성장하는 흐름을 만듭니다. 루기아처럼 강한 존재감과 책임감으로 공동체를 지켜냅니다." },
    ENTJ: { name: "리자몽", desc: "야심 찬 승부사. 목표를 향해 저돌적으로 나아가는 지휘형.", longDesc: "ENTJ인 당신은 방향을 정하면 빠르게 실행 구조를 만들고 결과를 끌어냅니다. 리자몽처럼 도전 상황에서 리더십이 강하게 드러납니다." },
  },
};

export const POKEMON_THEME_EN: ThemeMeta = {
  id: "pokemon",
  label: "Pokemon Gen 1-2",
  emoji: "⚡",
  gradient: "from-[#ef4444] to-[#facc15]",
  accentColor: "#ef4444",
  tags: ["Kanto", "Johto", "Pokemon"],
};

export const POKEMON_CONTENT_EN: ThemeContent = {
  questions: [
    { axis: "EI", prompt: "Your adventure starts in Pallet Town. First thought?", options: [{ value: "E", label: "I should battle trainers and make friends right away." }, { value: "I", label: "I will train quietly with my Pokemon first." }] },
    { axis: "EI", prompt: "At a Pokemon Center, you usually...", options: [{ value: "E", label: "Talk to other trainers and exchange tips." }, { value: "I", label: "Heal quickly, sort your Pokedex, and leave." }] },
    { axis: "EI", prompt: "A trainer says \"If we lock eyes, we battle!\" You...", options: [{ value: "E", label: "Accept excitedly and enjoy the showdown." }, { value: "I", label: "Battle calmly, then move on quietly." }] },
    { axis: "EI", prompt: "On the S.S. Aqua between Kanto and Johto, you...", options: [{ value: "E", label: "Explore the ship and meet everyone." }, { value: "I", label: "Stand on deck and plan your next Gym strategy." }] },
    { axis: "SN", prompt: "You hear rustling grass. Your first guess is...", options: [{ value: "S", label: "Likely a common low-level Pokemon nearby." }, { value: "N", label: "Could this be a rare or legendary encounter?" }] },
    { axis: "SN", prompt: "Professor Oak asks you to complete the Pokedex. You focus on...", options: [{ value: "S", label: "Catching one by one and filling each entry." }, { value: "N", label: "Understanding habitats, lore, and mysteries." }] },
    { axis: "SN", prompt: "You find ancient ruins and Unown text. You...", options: [{ value: "S", label: "Decode symbols step by step from visible clues." }, { value: "N", label: "Search for hidden meaning behind the symbols." }] },
    { axis: "SN", prompt: "When teaching a move, you prefer...", options: [{ value: "S", label: "Reliable power and accuracy." }, { value: "N", label: "Creative effects and mind-game potential." }] },
    { axis: "TF", prompt: "You lose to your rival. First response?", options: [{ value: "T", label: "Analyze matchups and fix the strategy." }, { value: "F", label: "Check on your Pokemon's feelings first." }] },
    { axis: "TF", prompt: "You see Team Rocket hurting Pokemon. You...", options: [{ value: "T", label: "Stop them with clear logic and decisive action." }, { value: "F", label: "Get emotional and jump in to protect Pokemon." }] },
    { axis: "TF", prompt: "A friend wants to release a weak Pokemon. You...", options: [{ value: "T", label: "From efficiency, replacing it can be practical." }, { value: "F", label: "You should stay with your partner to the end." }] },
    { axis: "TF", prompt: "Best way to build friendship with Pokemon?", options: [{ value: "T", label: "Train efficiently and win battles together." }, { value: "F", label: "Care, talk, and bond through warm interaction." }] },
    { axis: "JP", prompt: "Before a Gym challenge, your prep is...", options: [{ value: "J", label: "Type coverage and items fully planned." }, { value: "P", label: "Pack quickly and adapt on the spot." }] },
    { axis: "JP", prompt: "Entering a cave, your route style is...", options: [{ value: "J", label: "Follow a rule or mapped path." }, { value: "P", label: "Explore freely and improvise." }] },
    { axis: "JP", prompt: "Your bag organization looks like...", options: [{ value: "J", label: "Neatly categorized and easy to track." }, { value: "P", label: "Messy but workable in the moment." }] },
    { axis: "JP", prompt: "When setting your final adventure goal, you...", options: [{ value: "J", label: "Build a timeline to collect badges and clear the League." }, { value: "P", label: "Enjoy the journey and follow opportunities as they come." }] },
  ],
  results: {
    ISTJ: { name: "Dragonite", desc: "A reliable guardian with duty and consistency.", longDesc: "ISTJ types are steady and responsible, building trust through discipline. Like Dragonite, they protect the team with calm strength." },
    ISFJ: { name: "Blissey", desc: "A warm caretaker who supports others with devotion.", longDesc: "ISFJ types notice what others need and provide stability through care. Like Blissey, they heal and sustain the group quietly." },
    INFJ: { name: "Mew", desc: "A rare observer with deep insight and meaning focus.", longDesc: "INFJ types read hidden patterns and long-term direction. Like Mew, they bring unique perspective and gentle influence." },
    INTJ: { name: "Mewtwo", desc: "A strategic thinker focused on precision and mastery.", longDesc: "INTJ types structure complexity into clear long-term plans. Like Mewtwo, they combine power with deliberate control." },
    ISTP: { name: "Scyther", desc: "A practical specialist who proves skill through action.", longDesc: "ISTP types react fast and solve problems in real time. Like Scyther, they are precise, efficient, and independent." },
    ISFP: { name: "Ditto", desc: "A flexible creator with quiet sensitivity.", longDesc: "ISFP types adapt naturally while staying true to inner values. Like Ditto, they shift forms without losing identity." },
    INFP: { name: "Togepi", desc: "A gentle idealist who values peace and sincerity.", longDesc: "INFP types prioritize meaning, empathy, and authenticity. Like Togepi, they carry warmth that softens the world around them." },
    INTP: { name: "Alakazam", desc: "A deep analyst driven by logic and curiosity.", longDesc: "INTP types enjoy decoding systems and testing ideas. Like Alakazam, they lead with intellect and conceptual clarity." },
    ESTP: { name: "Arcanine", desc: "A bold executor with speed and courage.", longDesc: "ESTP types thrive in action and quick decision-making. Like Arcanine, they break through by moving first." },
    ESFP: { name: "Pikachu", desc: "A bright performer who energizes everyone nearby.", longDesc: "ESFP types connect instantly and raise the atmosphere. Like Pikachu, they bring joy, warmth, and momentum." },
    ENFP: { name: "Squirtle", desc: "A lively connector full of curiosity and spark.", longDesc: "ENFP types generate ideas and social energy quickly. Like Squirtle, they combine playfulness with natural leadership." },
    ENTP: { name: "Gengar", desc: "A playful disruptor who wins with creative twists.", longDesc: "ENTP types challenge assumptions and test bold possibilities. Like Gengar, they use wit and unpredictability as strategy." },
    ESTJ: { name: "Machamp", desc: "A disciplined manager who delivers concrete results.", longDesc: "ESTJ types organize people and systems for execution. Like Machamp, they are strong, structured, and dependable under pressure." },
    ESFJ: { name: "Clefable", desc: "A social caretaker who keeps harmony in the group.", longDesc: "ESFJ types maintain relationships with warmth and attention. Like Clefable, they protect group morale and cohesion." },
    ENFJ: { name: "Lugia", desc: "A guiding leader who protects and aligns others.", longDesc: "ENFJ types inspire growth while balancing the whole team. Like Lugia, they lead with vision and care." },
    ENTJ: { name: "Charizard", desc: "A driven commander who advances toward big goals.", longDesc: "ENTJ types set direction quickly and execute with force. Like Charizard, they combine ambition, momentum, and leadership." },
  },
};
